version: "3"
services:

  ############################# MY SQL ###############################                
  mysql:
    image: mysql:5.7
    build:
      context: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2019!"
      MYSQL_DATABASE: "dbpedidos"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/scripts:/data/application
      - ./mysql/data:/var/lib/mysql
    command: --init-file /data/application/init.sql
